### ISSUE TITLE
getAll() to support offset and reverse

### ISSUE THREAD

**Issue by staltz** [arj03/jitdb#9]
Use case:

```js
query(
  fromDB(db),
  and(type('post')),
  startFrom(30),
  ascending(),
  toCallback(cb)
)
```

- [x] Update logic in (internal method) `getAll()` to support `offset` and `reverse` arguments
- [x] Update `db.all()`
- [x] Update operator toCallback https://github.com/arj03/jitdb/blob/05e40a741838b2f5ddfe638ad7b1250a1b5fe26f/operators.js#L166
- [x] Update operator toPromise https://github.com/arj03/jitdb/blob/05e40a741838b2f5ddfe638ad7b1250a1b5fe26f/operators.js#L187

**Comment by staltz** [comment]
@arj03 One thing I found difficult to work with is that if we don't use `ascending()`, then the default behavior varies: if we do pagination, it will be assumed to be descending (newest to oldest, hence "getTop"), but if we don't do pagination, `db.all()` will assume ascending (oldest to newest). This difference in default behavior is complicated when the call to `db.all` or `db.paginate` is implicit inside the `toCallback`.

What if we fix the default direction to be either always-descending (requiring the developer to use `ascending()` in the chain when they want that) or always-ascending (requiring the developer to use `descending()` in the chain).

What do you think?

**Comment by arj03** [comment]
Hmm yeah, they really need to behave the same way. The other thing is just bad design. Good spotting. In SQL this are always ASC by default. And I think I subconsciously opted for default DESC because I'm so tired of writing that in SQL all the time ;-) I'm learning towards ASC by default as that is what most people would expect.
